### ISSUE TITLE
React Native for Android

### ISSUE THREAD

**Issue by elie222** [spencercarli/meteor-todos-react-native-2#1]
Would be great if we could get this running on Android too now that React Native for Android has been released.

**Comment by spencercarli** [comment]
Yeah that would be cool to try out. When I find the time I'll give it a go and see what I can come up with.

**Comment by tgoldenberg** [comment]
+1 this, plus now React Native for Android has the websocket module

**Comment by tgoldenberg** [comment]
By the way, great job on this. The previous way we were doing this was really hack-ish and this is really well organized.

**Comment by Taakn** [comment]
It works for me on Android, provided I use my IP address in the host (for instance 192.168.1.20) and not localhost or 127.0.0.1.

**Comment by spencercarli** [comment]
Closing this for now as it seems @Taakn was able to get it running. Please let me know otherwise if the app doesn't run on Android.
