### ISSUE TITLE
Error on run iOS

### ISSUE THREAD

**Issue by yogiben** [spencercarli/meteor-todos-react-native-2#13]
Running on iOS simulator:

`Image` has no propType for native prop `RCTImageView.defaultImageSrc` of native type `UIImage`

![image](https://cloud.githubusercontent.com/assets/1703155/12094324/d8e7965a-b2ff-11e5-91ab-c122838fa3a4.png)

**Comment by spencercarli** [comment]
Are you running the app as is from the repo or did you update React Native? If so, what version of RN did you update to?

There may be some breaking changes in the latest version of RN that I haven't taken care of yet.

**Comment by yogiben** [comment]
Tried it again today and it was working.

Sorry about that!
