### ISSUE TITLE
Error: Cannot find module 'babel-core/register'

### ISSUE THREAD

**Issue by elie222** [spencercarli/meteor-todos-react-native-2#15]
I get this error message when trying to run this project:
Error: Cannot find module 'babel-core/register'

Any ideas?

**Comment by spencercarli** [comment]
Hey I just updated the RN app to the latest version and ran into a variety of issues. I fixed those and am hoping it fixed this as well. Go ahead and clone the repo again and give it another shot. If it doesn't work please reopen! thanks

**Comment by elie222** [comment]
Works great now! Great job
