### ISSUE TITLE
npm run android doesn't work

### ISSUE THREAD

**Issue by elie222** [spencercarli/meteor-todos-react-native-2#17]
I get the following error when running:
⚡ npm run android

```
> ReactNativeTodos@0.0.1 android ....../meteor-todos-react-native/ReactNativeTodos
> react-native run-android

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "android"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ReactNativeTodos@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReactNativeTodos@0.0.1 android script 'react-native run-android'.
npm ERR! This is most likely a problem with the ReactNativeTodos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native run-android
npm ERR! You can get their info via:
npm ERR!     npm owner ls ReactNativeTodos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    ...../meteor-todos-react-native/ReactNativeTodos/npm-debug.log
```

And this in npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'android' ]
> 2 info using npm@2.14.7
> 3 info using node@v4.2.3
> 4 verbose run-script [ 'preandroid', 'android', 'postandroid' ]
> 5 info preandroid ReactNativeTodos@0.0.1
> 6 info android ReactNativeTodos@0.0.1
> 7 verbose unsafe-perm in lifecycle true
> 8 info ReactNativeTodos@0.0.1 Failed to exec android script
> 9 verbose stack Error: ReactNativeTodos@0.0.1 android: `react-native run-android`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:818:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 10 verbose pkgid ReactNativeTodos@0.0.1
> 11 verbose cwd ..../meteor-todos-react-native/ReactNativeTodos
> 12 error Darwin 15.2.0
> 13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "android"
> 14 error node v4.2.3
> 15 error npm  v2.14.7
> 16 error code ELIFECYCLE
> 17 error ReactNativeTodos@0.0.1 android: `react-native run-android`
> 17 error Exit status 1
> 18 error Failed at the ReactNativeTodos@0.0.1 android script 'react-native run-android'.
> 18 error This is most likely a problem with the ReactNativeTodos package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     react-native run-android
> 18 error You can get their info via:
> 18 error     npm owner ls ReactNativeTodos
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by spencercarli** [comment]
Two things to try:
- Can you upgrade to the latest node and npm?
- add `react-native-cli` to your dev dependencies `npm install react-native-cli --save-dev`

I've seen this issue before but I'm not sure what causes it

**Comment by spencercarli** [comment]
Going to close this. If you still run into the issue let me know.

Another option is to try running `react-native run-android` directly (rather than `npm run android`).
