### ISSUE TITLE
Explanation of authentication via ddp

### ISSUE THREAD

**Issue by yogiben** [spencercarli/meteor-todos-react-native-2#18]
The functionality `this.userId` on the meteor server comes from which part of the code?

**Comment by spencercarli** [comment]
That's coming from a `ddp.call` to the `login` method. `login` is exposed by the `accounts-password` package in the Meteor app.

The chunk of code that is related to that can be found here: https://github.com/spencercarli/meteor-todos-react-native/blob/master/ReactNativeTodos/app/config/db/accounts.js#L6

I've also got a blog post that digs into the Meteor authentication from React Native that you may find interesting: http://blog.differential.com/meteor-authentication-from-react-native/
