### ISSUE TITLE
SignUp screen

### ISSUE THREAD

**Issue by kristapslizanders** [spencercarli/meteor-todos-react-native-2#19]
SignUp screen doesn't show up!
When I enter app, it already shows to do list!

And also, why when I write new task, the letters doesn't also show up!

**Comment by spencercarli** [comment]
Have you logged in previously? If so that's the expected behavior.

And when you're adding text it doesn't show up? Are you using iOS or Android?

**Comment by kristapslizanders** [comment]
@spencercarli I'm using Android emulator - and yes, text doesn't show up.
And bout login - I am not logged in previously. When I turn on the app, it already shows the todo list screen.

**Comment by spencercarli** [comment]
That's strange. I'll try to take a look soon.

**Comment by kristapslizanders** [comment]
@spencercarli ok thanks, but I think that with sign up screen, there could be problem here maybe: http://prntscr.com/actg7p

But I have no idea, what to do with those letters...Why they don't show up, when I write something, only when I press enter, the topic shows up. 

It would be great, if you could help with these things.

**Comment by spencercarli** [comment]
what if in the `catch` statement you change it to

``` javascript
.catch((err) => {
  console.log('err', err);
  this.setState({loaded: false});
})
```

That's something I should definitely look into in this repo. If the app failed to connect to the ddp server we shouldn't set `loaded` to true

**Comment by kristapslizanders** [comment]
@spencercarli nothing changes, see? http://prntscr.com/actyqy

**Comment by kristapslizanders** [comment]
@spencercarli Tried to search smth on google, but nothing. Can't find the solution for those two problems!

**Comment by kristapslizanders** [comment]
@spencercarli Still waitin for some answers hah.

**Comment by spencercarli** [comment]
@kristapslizanders this has been fixed. Please checkout master again. I didn't realize that I was using the `ActionSheet` which is an ios only component. I've updated the repo so everything works on both ios and android.
