### ISSUE TITLE
Is the IOS folder generated ?

### ISSUE THREAD

**Issue by sahanDissanayake** [spencercarli/meteor-todos-react-native-2#2]
Hi Spencer, 

ReactNativeTodos/iOS/ folder is generated using Meteor ?

**Comment by spencercarli** [comment]
Hey! the entire `ReactNativeTodos` folder was generate with the React Native CLI - `react-native init ReactNativeTodos`.

The project structure has since changed a bit since public support of android was released. This hasn't been updated yet to match the new folder structure/support android.

**Comment by sahanDissanayake** [comment]
yep.. just wanted to confirm :+1: keep up the good work..

In your opinion this is how the folders should be structured for meteor app and the react-native ?

I'm new so just learning the best practices

**Comment by spencercarli** [comment]
I personally prefer to have the Meteor app in one repo and the React Native app in another repo (that's what I'm doing on a larger app). Purely for convenience sake I put both the meteor and RN app in the same repo here

**Comment by sahanDissanayake** [comment]
yup makes sense.. thank you
