### ISSUE TITLE
Tasks don't load on iPad Air 2, works fine in simulator

### ISSUE THREAD

**Issue by spspasov** [spencercarli/meteor-todos-react-native-2#20]
When I build and run the app on my iPad, the app loads correctly, but it just shows the view top view for adding a new list.

No tasks are visible, but the console in XCode shows the following message:

`[tid:com.facebook.React.JavaScript] DDP connection error!`

It works fine on the simulator, though.

**Comment by spencercarli** [comment]
I think this is related to where the app is looking for your ddp server. Replace `localhost` on [this line](https://github.com/spencercarli/meteor-todos-react-native/blob/9a5c7c8626c7951bcf5c1bfb449f1346fbf59d3c/ReactNativeTodos/app/config/db/lib/ddpClient.js#L6 with your Meteor server's IP address. 

Let me know if this helps!

**Comment by spspasov** [comment]
Aha, yes, I looked for that setting, but only found the one in AppDelegate.

I will try it on Monday and tell you if that fixes it.

**Comment by spencercarli** [comment]
Great! The file architecture isn't very intuitive (oh how a few months can change things!). There are some notes here https://github.com/spencercarli/react-native-meteor-boilerplate with instructions for running on a device.

**Comment by spspasov** [comment]
This fixed it, thanks!
