### ISSUE TITLE
What is the purpose of the meteor-to-dos folder?

### ISSUE THREAD

**Issue by smooJitter** [spencercarli/meteor-todos-react-native-2#21]
So what does the react-native app rely on from the meteor-todos folder especially the files in the client folder. From my understanding, the ReactNativeTodos folder replaces the responsibilities under meteor's "client" folder.

**Comment by spencercarli** [comment]
The files in `ReactNativeTodos` serve as the iOS and Android client. `meteor-todos` provides the web client and server - it serves as an api to the React Native app. Does that answer your question?

**Comment by smooJitter** [comment]
I think I understand.  It seems the most of the files in the meteor-todos folder are irrelevant meaning the react native app works with them. I wonder if the RN app would still run the ReactNativeTodos replaced the "client" folder under the meteor-todos. I'll try it as soon as I can. Thanks for the reply.

**Comment by spencercarli** [comment]
There might be some issues with that because the `meteor-todos/client` folder falls into the Meteor build system and it may try to compile the RN.

Think of the files in `meteor-todos/client` as siblings to `ReactNativeTodos`. They each serve their own unique purpose - one to build the web app and one to build the iOS and Android apps.

**Comment by smooJitter** [comment]
I see. I figured including there would be a problem with make a direct substitution.  So if the aim was just to build a RN app, then I probably wouldn't need the meteor-todos/client app.  Again, thanks for the reply.

**Comment by spencercarli** [comment]
Nope if you're just targeting RN then you don't need anything in `client`. Check out the boilerplate I put together (very bare bones meteor app). https://github.com/spencercarli/react-native-meteor-boilerplate
