### ISSUE TITLE
Todos do not save

### ISSUE THREAD

**Issue by tomtom87** [spencercarli/meteor-todos-react-native-2#24]
I'm trying to save a todo and although I can enter text, it doesn't save anywhere

**Comment by spencercarli** [comment]
Thanks for bringing this up. I experienced the same thing while trying to fix a different issue.

**Comment by spencercarli** [comment]
I think your error is that you're not connecting to the proper server. Make sure to connect to the right meteor server. You can change that here: https://github.com/spencercarli/meteor-todos-react-native/blob/master/ReactNativeTodos/app/config/db/lib/ddpClient.js#L7

Use either your machine's ip address or `localhost` (localhost only works for ios dev).

Let me know if that doesn't work for you.

**Comment by tomtom87** [comment]
thanks man! I will try this tomorrow and get back to you :)
