### ISSUE TITLE
Update to use latest React Native Meteor Boilerplate

### ISSUE THREAD

**Issue by spencercarli** [spencercarli/meteor-todos-react-native-2#27]
I would like to update this repo to use the [react native meteor boilerplate](https://github.com/spencercarli/react-native-meteor-boilerplate) at the core. Could also use some design improvements.

Anyone interested in contributing?

**Comment by smooJitter** [comment]
With design improvements?  Lol. What do you have in mind?  I sort of liked the unstyled look.

**Comment by spencercarli** [comment]
Haha yeah I thought that maybe things could be cleaned up :) I do like the raw nature of it... maybe it just needs a little bit of color? (I feel like a designer will cringe upon reading that, "let's just spritz it up a bit, really make it POP" lol)

**Comment by spencercarli** [comment]
Closing as part of the deprecation of this repo.
