### ISSUE TITLE
Client side is not react when modifying an array in collection to be [].

### ISSUE THREAD

**Issue by sandcforge** [spencercarli/meteor-todos-react-native-2#3]
Hi,
This is a great work. I just follow this example to make my own project meteor supported.
But I have met an issue here.
My collection is like
{ _id: 'bAJn7PkztXPmJMev7',
  name: '55555',
  price: 100.03,
  number: 1,
  type: 'bag',
  description: null,
  thumb: 'http://facebook.github.io/react/img/logo_og.png',
  images: [ 'assets-library://asset/asset.JPG?id=92C7E36A-24CA-4482-A557-C14ED969638A&ext=JPG' ],
  userId: 'vgucNAEy4wyeFmxHi' }

Suppose I need to remove the only item in 'images', making it []. Here is my step on the sever side.

 aa  = Lists.findOne({_id:'bAJn7PkztXPmJMev7'})
aa.name = '22'
aa.images = []
Lists.update({_id:'bAJn7PkztXPmJMev7'},{$set:aa}

I can see from the sever side that everything is correct, however, on the client side, 'name' is changed to '22', images is still the original value, which has one element.

Would you please take a look?

Thanks,
Chen

**Comment by sandcforge** [comment]
By the way, if I just assign images[0] to be another value, this is still fine. The client would response correctly. This issue only happens when 'images[0]' is removed from 'images', and 'images' is [].

**Comment by spencercarli** [comment]
Are you displaying the images? Or are you sure the array isn't updated on the client?

If you're displaying the images in the array maybe ios is caching them?

**Comment by sandcforge** [comment]
Thanks for your quick reply.
Yes, I am displaying the image. But I have checked the value from 'runSub', the result from sever is not updated, still the original value. Be notice that, when I modify the value of 'images[0]', it is reactive. The client would display the updated value. The issue only happens when I remove 'images[0]', making 'images' to be []. By the way, the 'client' here is react native client.

Thanks,
Sheng

**Comment by spencercarli** [comment]
Sheng, I'm not sure what's going on but I the last guess I could make is to make sure the code that is actually accessing `images[0]` is being rerun when the data changes. If you're iterating over the array it might not rerun whereas changing `images[0]` wouldn't require another run over the array? That's the best guess I've got

**Comment by sandcforge** [comment]
Hi spencercarli,
Sorry for the late reply. I am kind of busy with other stuff this week, and come back to this today.
The only case that does not work is that I remove the images[0], while it is working when I change the value of images[0]. I have no idea that the difference between removing an element in an array and change the value of that.
Do you mind that I share my code with you? And would you help me debug that? If so, I really appreciate your help.

Thanks,
Chen

**Comment by spencercarli** [comment]
Yeah you can share code and I'll take a look and hopefully be able to help you out.

**Comment by sandcforge** [comment]
Hi Spencer,
I have shared my code with you on bitbucket.

Please  take a look. I really appreciate your help.

Thanks,
Chen

**Comment by spencercarli** [comment]
Going to close this issue since we took the conversation offline and it's not related to this repo.
