### ISSUE TITLE
Separating Mongo Collections into files

### ISSUE THREAD

**Issue by swarthout** [spencercarli/meteor-todos-react-native-2#4]
Hello Spencer,
First off, I love the work you are doing integrating meteor with react native. I am excited to see how these two frameworks work with each other in the future. I was wondering if you had any advice about organizing my mongo collections into separate files and then importing them like:
import Todos from '../collections/todos'; 
or something. I am hoping to emulate the style found in benoitt's meteor webpack:
 https://github.com/thereactivestack/kickstart-simple
Do you have any ideas about how to support this? Thank you!

**Comment by spencercarli** [comment]
I don't have much advice to give here but in a larger project I'm involved with we've got a `db/collections` folder where each collection gets it's own file and we then import them from there.

An example would be:

```
import ddpClient from './lib/ddpClient';
import React from "react-native";

UserEvents = ddpClient.collections.userEvents;

export default UserEvents;
```

We're doing that so we can tie additional functions to UserEvents if we want to.
