### ISSUE TITLE
Can't run on physical device

### ISSUE THREAD

**Issue by nicholasalanbrown** [spencercarli/meteor-todos-react-native-2#5]
Hello:

This works terrific in the iOS Simulator but when trying to run on my iPhone (via Product > Run), I get this error:

```
Could not connect to development server. Ensure node server is running and available on the same network - run 'npm start' from react-native root.

http://localhost:8081/
index.ios.bundle

Could not connect to the server.

Any ideas?



```

**Comment by spencercarli** [comment]
Hey, this is something I don't currently have in the docs but to run on your device you need to replace `localhost` with your computer's IP address.

The two places it needs to be changed are 
- https://github.com/spencercarli/meteor-todos-react-native-2/blob/master/ReactNativeTodos/app/config/ddp.js#L8
- https://github.com/spencercarli/meteor-todos-react-native-2/blob/master/ReactNativeTodos/iOS/ReactNativeTodos/AppDelegate.m#L34

You can get your IP address by running `ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -1`

**Comment by nicholasalanbrown** [comment]
@spencercarli thanks so much, that worked like a charm!

I assume in a production setting I'd replace both of those "localhost"s with my server hostname, yes?

I've forked your repo and am working on expanding it into a good starting boilerplate. Thanks for the contribution to the community.

**Comment by nicholasalanbrown** [comment]
Another thought occurred to me, is there any good way to run the Xcode project with an environment variable so you don't have to update the code each time you switch machines? Not very familiar with Xcode/AppDelegate...

**Comment by spencercarli** [comment]
So in a production setting you'll need to change ddp.js to use a `url` rather than `host` and `port`. Where `url` is `wss://test.meteor.com/websocket`.

And in `AppDelete.m` you would uncomment line 46 (react native has more info on this).

RE: environment variables. I'm not sure but I really wish there was (so if you find out let me know!). In a larger app we have a settings file with all the config info we need and just change our environment info there.

**Comment by nicholasalanbrown** [comment]
Very helpful. I'll look into declaring environment variables in Xcode. Initial inspection suggest there's a way to do it. 

I have this working well, but I'm not seeing any hot code pushes. Is there something specific I need to do to make that happen?

**Comment by nicholasalanbrown** [comment]
Ah, I figured it out: http://stackoverflow.com/questions/29308757/is-it-possible-to-automatically-reload-the-app-in-react-native

**Comment by spencercarli** [comment]
I'm going to close since it seems you got the app running. Let me know if not

**Comment by nicholasalanbrown** [comment]
Indeed I did, thanks!

Just FYI, it took me a very long time to realize why `DeviceEventEmitter` wasn't working - your project is using a very old version of React Native (0.10.1). You may want to update if you're planning on maintaining this boilerplate. It's worth looking at a fresh app compiled on 0.14.0 when you do, as there are changes to `AppDelegate.m` and in the way images need to be saved and named.

I've forked your project here and will be pulling in these kind of updates: https://github.com/nicholasalanbrown/little-dipper

**Comment by spencercarli** [comment]
Thanks for pointing that out! I'm not planning on maintaining this version but am currently working on a new version of this (with Android support).

Hopefully I can cover a few other issues that have been brought up in the new version and distill it down to a boilerplate that can be more maintained and isn't as tied to the todos example. 

Now to find the time to actually finish it :smile:

**Comment by spencercarli** [comment]
@nicholasalanbrown hey just wanted to ping you and let you know I've updated the app to 0.14.2 of React Native. No android support still but it's one step closer.
