### ISSUE TITLE
Stopping Subscriptions?

### ISSUE THREAD

**Issue by nicholasalanbrown** [spencercarli/meteor-todos-react-native-2#6]
I've been able to follow this example successfully for Mongo subscriptions, queries, etc. The only issue I'm having is once I've started a subscription it persists even when I leave the component. The observer gets stopped but try as I might I can't get the subscription to stop and the data to be cleared from Minimongo-cache. I've tried things like:

```
ddp.subscribe('todos').stop()
```

to no avail. I could just subscribe to all of the data I might need in the app (which for my case actually might be a good idea since it's not too much) but for other use cases that could lead to serious performance degradation...

**Comment by spencercarli** [comment]
Hey! Thanks for bringing this up. I'll have to make note of this when I get the time to update this repo.

As for unsubscribing the `node-ddp-client` package provides and `unsubscribe` function. You could do this:

``` javascript
let sub = ddp.subscribe('todos');
ddp.unsubscribe(sub);
```

Here's the code from the package related to this https://github.com/hharnisc/node-ddp-client/blob/minimongo-cache/index.js#L394L418

**Comment by nicholasalanbrown** [comment]
Hmm, that didn't seem to work. I defined  new method in ddp.js like this:

```
ddp.unsubscribe = function(pubName) {
    ddpClient.unsubscribe(pubName);
};
```

...but when attempting to run `ddp.unsubscribe('todos') on the client, I get`undefined```

Not sure I'm going about this right. Also, it occurs to me that even if I stop the subscription, it would likely still leave data on the client and I'd want to be able to flush it to maintain performance...

**Comment by sunny-g** [comment]
`unsubscribe` takes a subscription id, which is returned from `ddp.subscribe`. But as you stated, it doesn't take care of cleaning up `ddp`-maintained collections for you.

**Comment by spencercarli** [comment]
@sunny-g is correct, `unsubscribe` needs the subscription id rather than the sub name.

You'll also have to clean up data manually. This is something I'm still trying to figure out - curious how Meteor does it?

**Comment by nicholasalanbrown** [comment]
Got it. I haven't quite figured out yet how to return the subscription ID, but I'm going to play with this more today. I'm not sure I'm looking at the right documentation...

As far as cleaning up data, it's not super important for my use case but it is something I want to understand. I'll report back if I figure this out.

**Comment by spencercarli** [comment]
I'm not sure that it's actually documented anywhere. Here's the source that may help https://github.com/hharnisc/node-ddp-client/blob/minimongo-cache/index.js#L412-L418

**Comment by sunny-g** [comment]
@nicholasalanbrown the subscription ID is what's returned from `ddp.subscribe` as such: https://github.com/hharnisc/node-ddp-client/blob/minimongo-cache/index.js#L409

**Comment by nicholasalanbrown** [comment]
Great, I think I'm closer to getting this, I'm just not sure where to place that `id` return/console.log in Spencer's example subscription:

```
    ddp.subscribe(subName)
      .then(() => {
        let listsObserver = ddp.collections.observe(() => {
          return ddp.collections.lists.find(query)
        });

        this.setState({listsObserver: listsObserver});

        listsObserver.subscribe((results) => {
          this.setState({lists: results});
        });
      });
```

Does a callback need to be added?

**Comment by sunny-g** [comment]
```
let subId = ddp.subscribe(subName)
  .then(() => {
    let listsObserver = ddp.collections.observe(() => {
      return ddp.collections.lists.find(query)
    });

    this.setState({
      listsObserver: listsObserver,
      subId: subId
    });

    listsObserver.subscribe((results) => {
      this.setState({lists: results});
    });
  });
```

then, in your `componentWillUnmount`:

```
if (this.state.listsObserver) {
  this.state.listsObserver.dispose();
  ddp.unsubscribe(this.state.subId);
}
```
