### ISSUE TITLE
Can't resume session with login token

### ISSUE THREAD

**Issue by nicholasalanbrown** [spencercarli/meteor-todos-react-native-2#7]
Not sure what the root cause of this is, but I get a crash and an error when the app tries to resume a login token:

```
[tid:com.facebook.React.AsyncLocalStorageQueue][RCTUtils.m:305] 
Error: {
    key = loginTokenExpires;
    message = "Values must be strings, got: 2016-02-04 16:38:55 +0000";
```

It looks like the login token is the wrong data type. Going to investigate further.

**Comment by spencercarli** [comment]
Very strange. I haven't seen this before... what version of React Native/ Meteor are you running?

Related to this [line](https://github.com/spencercarli/meteor-todos-react-native-2/blob/master/ReactNativeTodos/app/config/ddp.js#L106).

**Comment by spencercarli** [comment]
This should be fixed in the latest version of the app https://github.com/spencercarli/meteor-todos-react-native/blob/master/ReactNativeTodos/app/config/db/accounts.js#L24
